# Generated by Django 5.1.7 on 2025-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='is_public',
            field=models.BooleanField(choices=[(0, 'приватный'), (1, 'публичный')], default=0, verbose_name='виден ли модуль другим пользователям'),
        ),
    ]
