# Generated by Django 5.1.7 on 2025-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='is_public',
            field=models.BooleanField(choices=[(False, 'приватный'), (True, 'публичный')], default=0, verbose_name='Видимость'),
        ),
    ]
