# Generated by Django 5.1.7 on 2025-05-18 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_module_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
