version: "3.8"

services:
  django-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: django-backend
    container_name: django-backend
    restart: always
    command: "gunicorn core.config.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis  
    networks:
      - app-network
    expose:
      - "8000"

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - "5433:5432"
    networks:
      - app-network

  redis:  
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - django-backend
    networks:
      - app-network

volumes:
  db_data:
  redis_data:  

networks:
  app-network:
    driver: bridge